# Generated by Django 3.2.8 on 2022-04-05 11:27

import classes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_token', models.CharField(default='', max_length=500)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=classes.models.path_and_rename)),
                ('title', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('limit', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classrooms',
            },
        ),
    ]
