# Generated by Django 3.2.8 on 2022-04-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='password',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
