# Generated by Django 3.2.8 on 2022-05-20 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdata',
            name='exam_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examinfo'),
        ),
    ]
