# Generated by Django 3.2.8 on 2022-05-22 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0002_alter_examdata_exam_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinfo',
            name='finish_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='examinfo',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='ExamGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=64)),
                ('visible', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('exam_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
