# Generated by Django 3.2.8 on 2022-04-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examinfo_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examdata',
            old_name='questions',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='examdata',
            name='answers',
            field=models.CharField(max_length=128),
        ),
    ]
