# Generated by Django 3.2.8 on 2022-05-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20220522_1059'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='examgrades',
            table='exam_grades',
        ),
    ]
