# Generated by Django 3.2.8 on 2022-05-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_examgrades_exam_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='examgrades',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
