# Generated by Django 3.2.8 on 2022-05-26 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20220425_0128'),
        ('exams', '0007_examgrades_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinfo',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.classroom'),
            preserve_default=False,
        ),
    ]
