# Generated by Django 3.2.8 on 2022-06-03 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_examinfo_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examanswers',
            name='exam_data',
        ),
        migrations.AddField(
            model_name='examanswers',
            name='exam_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exams.examinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examanswers',
            name='answers',
            field=models.CharField(max_length=128),
        ),
    ]
