# Generated by Django 3.2.8 on 2022-07-07 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_auto_20220603_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinfo',
            name='finish_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='examinfo',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
