# Generated by Django 3.2.8 on 2022-07-08 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_auto_20220707_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinfo',
            name='finish_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='examinfo',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
